backend:
  name: git-gateway
  branch: main

local_backend: false

media_folder: "src/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "movies"
    label: "Movies"
    folder: "src/movies"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{ slug }}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tagline", name: "tagline", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Poster", name: "poster", widget: "image", required: false }
      - { label: "Director", name: "director", widget: "string", required: false }
      - { label: "Runtime", name: "runtime", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
    meta:
      layout:
        widget: hidden
        default: "layouts/movie.njk"

  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    extension: "njk"
    format: "frontmatter"
    slug: "{{ slug }}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "settings"
    label: "Settings"
    files:
      - label: "Site Settings"
        name: "site"
        file: "src/_data/site.json"
        fields:
          - { label: "Site name", name: "name", widget: "string" }
          - { label: "Tagline / Description", name: "description", widget: "string" }
          - { label: "Theme (daisyUI)", name: "theme", widget: "string", default: "dark", hint: "Ex: dark, light, synthwave, cupcake, corporate ..." }
          - { label: "Hero Title", name: "heroTitle", widget: "string" }
          - { label: "Hero Subtitle", name: "heroSubtitle", widget: "string" }
          - { label: "Hero Button Text", name: "heroButtonText", widget: "string", default: "See schedule" }
          - { label: "Hero Background", name: "heroBg", widget: "image", required: false, hint: "Leave empty for solid bg" }
