backend:
  name: github
  repo: philmltu/philm1
  branch: main

  # 👇 REQUIRED for GitHub Pages: point to your OAuth server (NOT your Pages site)
  # Examples:
  #   base_url: https://cms-auth.example.com
  #   auth_endpoint: /oauth/authorize
  #   (Your OAuth server’s README will tell you the exact path.)
  base_url: https://YOUR-OAUTH-SERVER.DOMAIN
  auth_endpoint: /oauth/authorize

# Optional: if you also want local editing without GitHub auth,
# keep this true for local dev and run `npx decap-cms-proxy-server`
# local_backend: true

media_folder: "src/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow  # drafts/review flow (optional)

collections:
  - name: "movies"
    label: "Movies"
    folder: "src/movies"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tagline", name: "tagline", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Poster", name: "poster", widget: "image", required: false }
      - { label: "Director", name: "director", widget: "string", required: false }
      - { label: "Runtime", name: "runtime", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "src/pages/about.njk"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body (HTML/Nunjucks ok)", name: "body", widget: "text" }
