backend:
  name: git-gateway
  branch: main

local_backend: true
publish_mode: simple

media_folder: "src/uploads"
public_folder: "/uploads"

collections:
  - name: "movies"
    label: "Movies"
    folder: "src/movies"
    create: true
    extension: "md"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    # delete: false 
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Poster", name: "poster", widget: "image", required: false }
      - { label: "Runtime", name: "runtime", widget: "string", required: false }
      - { label: "Tagline", name: "tagline", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "SKRIV INTE NÅGOT HÄR!!)", name: "layout", widget: "string", default: "layouts/movie.njk", required: false }

  - name: "team"
    label: "Team Member"
    folder: "src/team"
    create: true
    extension: "md"
    slug: "{{slug}}"
    # delete: false   <-- REMOVE this line if present
    fields:
      - { label: "Name",  name: "name",  widget: "string" }
      - { label: "Role",  name: "role",  widget: "string", required: false }
      - { label: "Photo", name: "photo", widget: "image", required: false }
      - { label: "Order", name: "order", widget: "number", valueType: "int", min: 0, default: 0 }
      - { label: "Bio",   name: "body",  widget: "markdown", required: false }

