backend:
  name: git-gateway
  branch: main

local_backend: true
publish_mode: editorial_workflow

media_folder: "src/uploads"
public_folder: "/uploads"

collections:
  # Movies (date + slug in filename; enforce movie layout via hidden field)
  - name: "movies"
    label: "Movies"
    folder: "src/movies"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/movie.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tagline", name: "tagline", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Poster", name: "poster", widget: "image", required: false }
      - { label: "Director", name: "director", widget: "string", required: false }
      - { label: "Runtime", name: "runtime", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  # Pages (create/edit arbitrary pages)
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    extension: "njk"
    format: "frontmatter"
    slug: "{{ slug }}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  # Global site settings (editable from CMS)
  - name: "settings"
    label: "Settings"
    files:
      - label: "Site Settings"
        name: "site"
        file: "src/_data/site.json"
        fields:
          - { label: "Site name", name: "name", widget: "string" }
          - { label: "Tagline / Description", name: "description", widget: "string" }
          - { label: "Theme (daisyUI)", name: "theme", widget: "string", default: "dark" }
          - { label: "Hero Title", name: "heroTitle", widget: "string" }
          - { label: "Hero Subtitle", name: "heroSubtitle", widget: "string" }
          - { label: "Hero Button Text", name: "heroButtonText", widget: "string", default: "See schedule" }
          - { label: "Hero Background", name: "heroBg", widget: "image", required: false }
          - { label: "Hitract URL (passive)", name: "hitractUrl", widget: "string" }      # ← new
          - { label: "Active form URL", name: "activeFormUrl", widget: "string" }          # ← new



  # Edit header/footer/base directly in CMS (advanced)
  - name: "theme"
    label: "Theme Files"
    files:
      - label: "Header"
        name: "header"
        file: "src/_includes/partials/header.njk"
        fields:
          - { label: "Header (Nunjucks)", name: "body", widget: "code", default_language: "html", output_code_only: true }
      - label: "Footer"
        name: "footer"
        file: "src/_includes/partials/footer.njk"
        fields:
          - { label: "Footer (Nunjucks)", name: "body", widget: "code", default_language: "html", output_code_only: true }
      - label: "Base Layout"
        name: "base"
        file: "src/_includes/layouts/base.njk"
        fields:
          - { label: "Base Layout (Nunjucks)", name: "body", widget: "code", default_language: "html", output_code_only: true }


