backend:
  name: git-gateway
  branch: main

local_backend: false

media_folder: "src/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "movies"
    label: "Movies"
    folder: "src/movies"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{ slug }}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tagline", name: "tagline", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Poster", name: "poster", widget: "image", required: false }
      - { label: "Director", name: "director", widget: "string", required: false }
      - { label: "Runtime", name: "runtime", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
    meta:
      layout:
        widget: hidden
        default: "layouts/movie.njk"
